import AuthService from '#services/auth_service'
import { forgotPasswordValidator, resetPasswordValidator } from '#validators/auth_validator'
import type { HttpContext } from '@adonisjs/core/http'
import { inject } from '@adonisjs/core'
import { type PageObject } from '@adonisjs/inertia/types'

/**
 * Handles password recovery and password reset workflows.
 *
 * Responsibilities:
 * - Display password recovery pages.
 * - Accept password reset requests.
 * - Validate password reset links.
 * - Coordinate password updates through the authentication service.
 */
@inject()
export default class PasswordResetController {
  constructor(protected authService: AuthService) {}

  /**
   * Display the forgot-password page.
   *
   * This page allows customers to request a password reset link using
   * their registered phone number.
   *
   * @param ctx - HTTP request context.
   * @returns The forgot-password page.
   */
  async create({ inertia }: HttpContext): Promise<string | PageObject<{}>> {
    return inertia.render('auth/forgot_password', {})
  }

  /**
   * Process a password reset request.
   *
   * When the submitted phone number belongs to a registered account,
   * a password reset link is delivered through WhatsApp. A generic
   * response is returned regardless of whether the account exists to
   * avoid disclosing account ownership information.
   *
   * @param ctx - HTTP request context.
   * @returns A redirect response back to the originating page.
   */
  async store({ request, response, session }: HttpContext): Promise<void> {
    const payload = await request.validateUsing(forgotPasswordValidator)

    await this.authService.requestPasswordReset(payload)
    session.flash(
      'success',
      'Jika akun dengan nomor telepon tersebut ada, tautan reset kata sandi telah dikirim melalui WhatsApp.'
    )

    return response.redirect().back()
  }

  /**
   * Display the password reset form.
   *
   * Access is only granted when the request contains a valid signed URL
   * and the required account identifier. Invalid or expired reset links
   * are treated as non-existent resources.
   *
   * @param ctx - HTTP request context.
   * @returns The password reset page or a not-found page when the reset
   * link is invalid.
   */
  async edit({ request, inertia }: HttpContext): Promise<string | PageObject<{}>> {
    const phone = request.qs().phone as string
    if (!request.hasValidSignature() || !phone) {
      return inertia.render('errors/not_found', {})
    }

    return inertia.render('auth/reset_password', {})
  }

  /**
   * Complete the password reset process using a validated reset link.
   *
   * The request must originate from a valid signed URL generated by the
   * application. Upon successful password update, the customer is redirected
   * to the login page.
   *
   * Invalid or expired reset links are treated as non-existent resources.
   *
   * @param ctx - HTTP request context.
   * @returns A redirect response to the login page or a not-found page when
   * the reset link is invalid.
   */
  async update({
    request,
    response,
    inertia,
  }: HttpContext): Promise<void | string | PageObject<{}>> {
    const phone = request.qs().phone as string
    if (!request.hasValidSignature() || !phone) {
      return inertia.render('errors/not_found', {})
    }

    const payload = await request.validateUsing(resetPasswordValidator)

    await this.authService.resetPassword(payload, phone)

    return response.redirect().toRoute('session.create')
  }
}
