/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Phone: () => import('#controllers/admin/phone_controller'),
    Profile: () => import('#controllers/admin/profile_controller'),
  },
  auth: {
    PasswordReset: () => import('#controllers/auth/password_reset_controller'),
    Session: () => import('#controllers/auth/session_controller'),
    Signup: () => import('#controllers/auth/signup_controller'),
  },
  customer: {
    Address: () => import('#controllers/customer/address_controller'),
    Order: () => import('#controllers/customer/order_controller'),
    Password: () => import('#controllers/customer/password_controller'),
    Phone: () => import('#controllers/customer/phone_controller'),
    Profile: () => import('#controllers/customer/profile_controller'),
    Transaction: () => import('#controllers/customer/transaction_controller'),
  },
  staff: {
    Inspection: () => import('#controllers/staff/inspection_controller'),
    Order: () => import('#controllers/staff/order_controller'),
    Phone: () => import('#controllers/staff/phone_controller'),
    Profile: () => import('#controllers/staff/profile_controller'),
    Transaction: () => import('#controllers/staff/transaction_controller'),
    Trip: () => import('#controllers/staff/trip_controller'),
  },
  webhooks: {
    Transaction: () => import('#controllers/webhooks/transaction_controller'),
  },
}
