/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import OrderCreated from '#events/order_created'
import OrderPaid from '#events/order_paid'
import OrderPriceCorrected from '#events/order_price_corrected'
import OrderStatusChanged from '#events/order_status_changed'

export const events = {
  OrderCreated: OrderCreated,
  OrderPaid: OrderPaid,
  OrderPriceCorrected: OrderPriceCorrected,
  OrderStatusChanged: OrderStatusChanged,
}
