/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import { CatalogueCategory, CatalogueType } from '#enums/catalogue_enum'
import { ItemType } from '#enums/item_enum'
import { ActionName } from '#enums/order_action_enum'
import { TaskType } from '#enums/task_enum'
import { OrderStatus, OrderType } from '#enums/order_enum'
import { PaymentMethod, TransactionStatus } from '#enums/transaction_enum'
import { Role } from '#enums/role_enum'

export class AddressSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isActive',
    'latitude',
    'longitude',
    'name',
    'note',
    'phone',
    'street',
    'updatedAt',
    'userId',
  ] as const
  $columns = AddressSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare name: string
  @column()
  declare note: string | null
  @column()
  declare phone: string
  @column()
  declare street: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CatalogueSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'description',
    'id',
    'name',
    'price',
    'type',
    'updatedAt',
  ] as const
  $columns = CatalogueSchema.$columns
  @column()
  declare category: CatalogueCategory
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare type: CatalogueType
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItemSchema extends BaseModel {
  static $columns = [
    'brand',
    'createdAt',
    'id',
    'material',
    'model',
    'note',
    'orderId',
    'size',
    'type',
    'updatedAt',
  ] as const
  $columns = ItemSchema.$columns
  @column()
  declare brand: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare material: string | null
  @column()
  declare model: string
  @column()
  declare note: string | null
  @column()
  declare orderId: number
  @column()
  declare size: string
  @column()
  declare type: ItemType
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OperationalAreaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = OperationalAreaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderActionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'name',
    'note',
    'orderId',
    'photoPath',
    'updatedAt',
    'userId',
  ] as const
  $columns = OrderActionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: ActionName
  @column()
  declare note: string | null
  @column()
  declare orderId: number
  @column()
  declare photoPath: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = [
    'catalogueId',
    'condition',
    'createdAt',
    'id',
    'itemId',
    'name',
    'orderId',
    'price',
    'subtotal',
    'updatedAt',
  ] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare catalogueId: number
  @column()
  declare condition: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare name: string
  @column()
  declare orderId: number
  @column()
  declare price: string
  @column()
  declare subtotal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'addressId',
    'claimedAt',
    'claimedBy',
    'claimedTask',
    'createdAt',
    'customerName',
    'customerPhone',
    'id',
    'orderNumber',
    'pickupDate',
    'status',
    'totalPrice',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare addressId: number | null
  @column.dateTime()
  declare claimedAt: DateTime | null
  @column()
  declare claimedBy: number | null
  @column()
  declare claimedTask: TaskType | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderNumber: string
  @column.date()
  declare pickupDate: DateTime | null
  @column()
  declare status: OrderStatus
  @column()
  declare totalPrice: string | null
  @column()
  declare type: OrderType
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SpatialRefSySchema extends BaseModel {
  static $columns = ['authName', 'authSrid', 'proj4Text', 'srid', 'srtext'] as const
  $columns = SpatialRefSySchema.$columns
  @column()
  declare authName: string | null
  @column()
  declare authSrid: number | null
  @column()
  declare proj4Text: string | null
  @column({ isPrimary: true })
  declare srid: number
  @column()
  declare srtext: string | null
}

export class TransactionSchema extends BaseModel {
  static $columns = [
    'cashReceived',
    'createdAt',
    'id',
    'midtransOrderId',
    'midtransTransactionId',
    'orderId',
    'paymentMethod',
    'qrCode',
    'status',
    'updatedAt',
  ] as const
  $columns = TransactionSchema.$columns
  @column()
  declare cashReceived: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare midtransOrderId: string | null
  @column()
  declare midtransTransactionId: string | null
  @column()
  declare orderId: number
  @column()
  declare paymentMethod: PaymentMethod
  @column()
  declare qrCode: string | null
  @column()
  declare status: TransactionStatus
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isActive',
    'name',
    'password',
    'passwordChangedAt',
    'phone',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column()
  declare phone: string
  @column()
  declare role: Role
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
