/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddressSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isActive',
    'latitude',
    'longitude',
    'name',
    'note',
    'phone',
    'street',
    'updatedAt',
    'userId',
  ] as const
  $columns = AddressSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column()
  declare note: string | null
  @column()
  declare phone: string
  @column()
  declare street: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ItemSchema extends BaseModel {
  static $columns = [
    'brand',
    'condition',
    'createdAt',
    'id',
    'material',
    'model',
    'note',
    'size',
    'type',
    'updatedAt',
  ] as const
  $columns = ItemSchema.$columns
  @column()
  declare brand: string
  @column()
  declare condition: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare material: string | null
  @column()
  declare model: string
  @column()
  declare note: string | null
  @column()
  declare size: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'title', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OrderActionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'name',
    'note',
    'orderId',
    'photoPath',
    'staffId',
    'updatedAt',
  ] as const
  $columns = OrderActionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare note: string | null
  @column()
  declare orderId: number
  @column()
  declare photoPath: string | null
  @column()
  declare staffId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'itemId',
    'name',
    'orderId',
    'price',
    'serviceId',
    'subtotal',
    'updatedAt',
  ] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare name: string
  @column()
  declare orderId: number
  @column()
  declare price: number
  @column()
  declare serviceId: number
  @column()
  declare subtotal: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'addressId',
    'createdAt',
    'customerName',
    'customerPhone',
    'id',
    'lockedById',
    'lockedTask',
    'lockedUntil',
    'orderNumber',
    'pickupDate',
    'status',
    'totalPrice',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare addressId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lockedById: number | null
  @column()
  declare lockedTask: string | null
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare orderNumber: string
  @column.date()
  declare pickupDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalPrice: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ServiceSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'description',
    'id',
    'name',
    'price',
    'type',
    'updatedAt',
  ] as const
  $columns = ServiceSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TransactionSchema extends BaseModel {
  static $columns = [
    'cashReceived',
    'createdAt',
    'id',
    'midtransOrderId',
    'midtransTransactionId',
    'orderId',
    'paymentMethod',
    'qrCode',
    'status',
    'updatedAt',
  ] as const
  $columns = TransactionSchema.$columns
  @column()
  declare cashReceived: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare midtransOrderId: string | null
  @column()
  declare midtransTransactionId: string | null
  @column()
  declare orderId: number
  @column()
  declare paymentMethod: string
  @column()
  declare qrCode: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isActive',
    'name',
    'password',
    'passwordChangedAt',
    'phone',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column()
  declare phone: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
