/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AddressTransformer from '#transformers/address_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type CatalogueTransformer from '#transformers/catalogue_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Address = InferData<AddressTransformer>
  export namespace Address {
    export type Variants = InferVariants<AddressTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Catalogue = InferData<CatalogueTransformer>
  export namespace Catalogue {
    export type Variants = InferVariants<CatalogueTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
